import { StyleSheet, Dimensions } from "react-native";

const { width, height } = Dimensions.get("window");

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#000",
  },
  backgroundImage: {
    flex: 1,
    width: "100%",
    height: "100%",
  },
  overlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(0, 0, 0, 0.7)",
  },
  floatingElement: {
    position: "absolute",
    width: 100,
    height: 100,
    borderRadius: 50,
    backgroundColor: "rgba(74, 158, 255, 0.1)",
    borderWidth: 1,
    borderColor: "rgba(74, 158, 255, 0.3)",
  },
  floatingElement1: {
    top: "15%",
    right: "10%",
  },
  floatingElement2: {
    bottom: "20%",
    left: "5%",
    width: 60,
    height: 60,
    borderRadius: 30,
  },
  contentContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 30,
  },
  titleContainer: {
    alignItems: "center",
    marginBottom: 50,
  },
  title: {
    fontSize: 32,
    fontWeight: "bold",
    color: "#FFBF00",
    letterSpacing: 3,
    textShadowColor: "rgba(0, 0, 0, 0.8)",
    textShadowOffset: { width: 2, height: 2 },
    textShadowRadius: 4,
  },
  subtitle: {
    fontSize: 14,
    color: "#888",
    letterSpacing: 2,
    marginTop: 5,
  },
  titleUnderline: {
    width: 150,
    height: 2,
    backgroundColor: "#4A9EFF",
    marginTop: 10,
  },
  glassContainer: {
    width: "100%",
    backgroundColor: "rgba(255, 255, 255, 0.1)",
    backdropFilter: "blur(10px)",
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.2)",
    padding: 30,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 10,
    },
    shadowOpacity: 0.3,
    shadowRadius: 20,
    elevation: 10,
  },
  formHeader: {
    flexDirection: "row",
    marginBottom: 30,
    backgroundColor: "rgba(0, 0, 0, 0.3)",
    borderRadius: 25,
    padding: 3,
  },
  toggleButton: {
    flex: 1,
    paddingVertical: 12,
    alignItems: "center",
    borderRadius: 22,
    transition: "all 0.3s ease",
  },
  activeToggle: {
    backgroundColor: "#FFBF00",
  },
  toggleText: {
    color: "rgba(255, 255, 255, 0.6)",
    fontSize: 14,
    fontWeight: "600",
    letterSpacing: 1,
  },
  activeToggleText: {
    color: "#fff",
  },
  inputContainer: {
    marginBottom: 25,
  },
  input: {
    backgroundColor: "rgba(255, 255, 255, 0.1)",
    borderRadius: 15,
    paddingHorizontal: 20,
    paddingVertical: 15,
    marginBottom: 15,
    color: "#fff",
    fontSize: 16,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.2)",
    transition: "all 0.2s ease",
  },
  authButton: {
    backgroundColor: "#FFBF00",
    paddingVertical: 16,
    borderRadius: 25,
    alignItems: "center",
    marginBottom: 15,
    shadowColor: "#4A9EFF",
    shadowOffset: {
      width: 0,
      height: 5,
    },
    shadowOpacity: 0.4,
    shadowRadius: 10,
    elevation: 8,
  },
  authButtonText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "bold",
    letterSpacing: 1,
  },
  loginButtonText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "bold",
    letterSpacing: 1,
  },
  loadingContainer: {
    flexDirection: "row",
    alignItems: "center",
  },
  forgotPassword: {
    alignItems: "center",
  },
  forgotPasswordText: {
    color: "rgba(255, 255, 255, 0.7)",
    fontSize: 14,
  },
  guestButton: {
    marginTop: 30,
    paddingVertical: 15,
    paddingHorizontal: 30,
    borderRadius: 25,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.3)",
    backgroundColor: "rgba(255, 255, 255, 0.05)",
  },
  guestButtonText: {
    color: "rgba(255, 255, 255, 0.8)",
    fontSize: 14,
    textAlign: "center",
    letterSpacing: 1,
  },
  errorMsgBox: {
    flexDirection: "row",
    alignItems: "center",
    alignSelf: "stretch",
    backgroundColor: "rgba(255, 56, 93, 0.85)", // Brighter red-pink tone
    borderRadius: 10,
    paddingVertical: 10,
    paddingHorizontal: 16,
    marginVertical: 10,
    elevation: 2, // Android shadow
    shadowColor: "#FF375F", // iOS shadow
    shadowOpacity: 0.25,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 6,
    borderWidth: 1.2,
    borderColor: "rgba(255,255,255,0.18)",
    minHeight: 48,
  },
  errorMsgText: {
    color: "#fff",
    fontSize: 15,
    flex: 1,
    textAlign: "left",
    fontWeight: "600",
    letterSpacing: 0.2,
    marginLeft: 8,
  },
  errorIcon: {
    marginRight: 8,
  },

  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.85)",
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 20,
  },
  modalContainer: {
    width: "100%",
    maxWidth: 400,
    backgroundColor: "rgba(255, 255, 255, 0.12)",
    backdropFilter: "blur(20px)",
    borderRadius: 25,
    borderWidth: 1.5,
    borderColor: "rgba(255, 255, 255, 0.25)",
    padding: 30,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 15,
    },
    shadowOpacity: 0.5,
    shadowRadius: 25,
    elevation: 15,
  },
  modalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 10,
  },
  modalTitle: {
    fontSize: 26,
    fontWeight: "bold",
    color: "#FFBF00",
    letterSpacing: 1.5,
    textShadowColor: "rgba(0, 0, 0, 0.5)",
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 3,
  },
  closeButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: "rgba(255, 255, 255, 0.1)",
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.2)",
  },
  modalSubtitle: {
    fontSize: 14,
    color: "rgba(255, 255, 255, 0.7)",
    marginBottom: 25,
    lineHeight: 20,
    letterSpacing: 0.5,
  },
  otpInput: {
    backgroundColor: "rgba(255, 255, 255, 0.15)",
    borderRadius: 15,
    paddingHorizontal: 20,
    paddingVertical: 18,
    marginBottom: 20,
    color: "#fff",
    fontSize: 24,
    fontWeight: "600",
    textAlign: "center",
    letterSpacing: 8,
    borderWidth: 1.5,
    borderColor: "rgba(255, 255, 255, 0.3)",
  },
  verifyButton: {
    backgroundColor: "#FFBF00",
    paddingVertical: 16,
    borderRadius: 25,
    alignItems: "center",
    marginBottom: 15,
    shadowColor: "#FFBF00",
    shadowOffset: {
      width: 0,
      height: 6,
    },
    shadowOpacity: 0.5,
    shadowRadius: 12,
    elevation: 10,
  },
  buttonText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "bold",
    letterSpacing: 1.5,
  },
  resendButton: {
    paddingVertical: 12,
    alignItems: "center",
    backgroundColor: "rgba(255, 255, 255, 0.05)",
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.2)",
  },
  resendButtonText: {
    color: "#FFBF00",
    fontSize: 14,
    fontWeight: "600",
    letterSpacing: 1,
  },
  successMsgBox: {
    flexDirection: "row",
    alignItems: "center",
    alignSelf: "stretch",
    backgroundColor: "rgba(76, 175, 80, 0.85)",
    borderRadius: 10,
    paddingVertical: 10,
    paddingHorizontal: 16,
    marginVertical: 10,
    elevation: 2,
    shadowColor: "#4CAF50",
    shadowOpacity: 0.25,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 6,
    borderWidth: 1.2,
    borderColor: "rgba(255, 255, 255, 0.18)",
    minHeight: 48,
  },
  successMsgText: {
    color: "#fff",
    fontSize: 15,
    flex: 1,
    textAlign: "left",
    fontWeight: "600",
    letterSpacing: 0.2,
    marginLeft: 8,
  },
});
